export {
    empty as _IGenerator,
    empty as _IBuilder,
    empty as IGeneratorVNode,
    empty as IGeneratorControlNode,
    empty as TGeneratorNode,
    empty as htmlNode,
    empty as controlNode,
    empty as textNode,
    empty as TClosure,
    empty as createGenerator,
    empty as CommonUtils,
    empty as RequireHelper,
    empty as invisibleNodeTagName,
    empty as ConfigResolver,
    empty as _ForExecutorCompatible,
    empty as onElementMount,
    empty as onElementUnmount
} from 'UICommon/Empty';
