/**
 * @kaizen_zone a35eec2e-f16e-4783-9297-975d0fadc26b
 */
// список событий, который поддерживает react
// https://ru.reactjs.org/docs/events.html
export const reactEventList: string[] = [
    'onCopy',
    'onCut',
    'onPaste',
    'onCompositionEnd',
    'onCompositionStart',
    'onCompositionUpdate',
    'onKeyDown',
    'onKeyPress',
    'onKeyUp',
    'onFocus',
    'onBlur',
    'onChange',
    'onInput',
    'onInvalid',
    'onReset',
    'onSubmit',
    'onError',
    'onLoad',
    'onClick',
    'onContextMenu',
    'onDoubleClick',
    'onDrag',
    'onDragEnd',
    'onDragEnter',
    'onDragExit',
    'onDragLeave',
    'onDragOver',
    'onDragStart',
    'onDrop',
    'onMouseDown',
    'onMouseEnter',
    'onMouseLeave',
    'onMouseMove',
    'onMouseOut',
    'onMouseOver',
    'onMouseUp',
    'onPointerDown',
    'onPointerMove',
    'onPointerUp',
    'onPointerCancel',
    'onGotPointerCapture',
    'onLostPointerCapture',
    'onPointerEnter',
    'onPointerLeave',
    'onPointerOver',
    'onPointerOut',
    'onSelect',
    'onTouchCancel',
    'onTouchEnd',
    'onTouchMove',
    'onTouchStart',
    'onScroll',
    'onWheel',
    'onAbort',
    'onCanPlay',
    'onCanPlayThrough',
    'onDurationChange',
    'onEmptied',
    'onEncrypted',
    'onEnded',
    'onLoadedData',
    'onLoadedMetadata',
    'onLoadStart',
    'onPause',
    'onPlay',
    'onPlaying',
    'onProgress',
    'onRateChange',
    'onSeeked',
    'onSeeking',
    'onStalled',
    'onSuspend',
    'onTimeUpdate',
    'onVolumeChange',
    'onWaiting',
    'onLoad',
    'onAnimationStart',
    'onAnimationEnd',
    'onAnimationIteration',
    'onTransitionEnd',
    'onToggle',
];

export const wasabyEventIntersection = {
    'on:copy': 'onCopy',
    'on:cut': 'onCut',
    'on:paste': 'onPaste',
    'on:compositionend': 'onCompositionEnd',
    'on:compositionstart': 'onCompositionStart',
    'on:compositionupdate': 'onCompositionUpdate',
    'on:keydown': 'onKeyDown',
    'on:keypress': 'onKeyPress',
    'on:keyup': 'onKeyUp',
    'on:focus': 'onFocus',
    'on:focusin': 'onFocus',
    'on:blur': 'onBlur',
    'on:focusout': 'onBlur',
    'on:change': 'onChange',
    'on:input': 'onInput',
    'on:invalid': 'onInvalid',
    'on:reset': 'onReset',
    'on:submit': 'onSubmit',
    'on:error': 'onError',
    'on:click': 'onClick',
    'on:contextmenu': 'onContextMenu',
    'on:doubleclick': 'onDoubleClick',
    'on:dblclick': 'onDoubleClick',
    'on:drag': 'onDrag',
    'on:dragend': 'onDragEnd',
    'on:dragenter': 'onDragEnter',
    'on:dragexit': 'onDragExit',
    'on:dragleave': 'onDragLeave',
    'on:dragover': 'onDragOver',
    'on:dragstart': 'onDragStart',
    'on:drop': 'onDrop',
    'on:mousedown': 'onMouseDown',
    'on:mousedowncapture': 'onMouseDownCapture',
    'on:mouseenter': 'onMouseEnter',
    'on:mouseleave': 'onMouseLeave',
    'on:mousemove': 'onMouseMove',
    'on:mouseout': 'onMouseOut',
    'on:mouseover': 'onMouseOver',
    'on:mouseup': 'onMouseUp',
    'on:pointerdown': 'onPointerDown',
    'on:pointermove': 'onPointerMove',
    'on:pointerup': 'onPointerUp',
    'on:pointercancel': 'onPointerCancel',
    'on:gotpointercapture': 'onGotPointerCapture',
    'on:lostpointercapture': 'onLostPointerCapture',
    'on:pointerenter': 'onPointerEnter',
    'on:pointerleave': 'onPointerLeave',
    'on:pointerover': 'onPointerOver',
    'on:pointerout': 'onPointerOut',
    'on:select': 'onSelect',
    'on:touchcancel': 'onTouchCancel',
    'on:touchend': 'onTouchEnd',
    'on:touchmove': 'onTouchMove',
    'on:touchstart': 'onTouchStart',
    'on:scroll': 'onScroll',
    'on:wheel': 'onWheel',
    'on:abort': 'onAbort',
    'on:canplay': 'onCanPlay',
    'on:canplaythrough': 'onCanPlayThrough',
    'on:durationchange': 'onDurationChange',
    'on:emptied': 'onEmptied',
    'on:encrypted': 'onEncrypted',
    'on:ended': 'onEnded',
    'on:loadeddata': 'onLoadedData',
    'on:loadedmetadata': 'onLoadedMetadata',
    'on:loadstart': 'onLoadStart',
    'on:lause': 'onPause',
    'on:play': 'onPlay',
    'on:playing': 'onPlaying',
    'on:progress': 'onProgress',
    'on:patechange': 'onRateChange',
    'on:seeked': 'onSeeked',
    'on:seeking': 'onSeeking',
    'on:stalled': 'onStalled',
    'on:suspend': 'onSuspend',
    'on:timeupdate': 'onTimeUpdate',
    'on:volumechange': 'onVolumeChange',
    'on:waiting': 'onWaiting',
    'on:load': 'onLoad',
    'on:animationstart': 'onAnimationStart',
    'on:animationend': 'onAnimationEnd',
    'on:animationiteration': 'onAnimationIteration',
    'on:transitionend': 'onTransitionEnd',
    'on:toggle': 'onToggle',
};
